In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [9]:
df = pd.DataFrame({'Color': ['Blue','Red','Green','Blue','Green','Blue','Blue'], 'Target':[1,0,1,1,1,0,1]})
df

   Color  Target
0   Blue       1
1    Red       0
2  Green       1
3   Blue       1
4  Green       1
5   Blue       0
6   Blue       1

In [6]:
le = LabelEncoder()
df['Color'] = le.fit_transform(df['Color'])

In [7]:
df

   Color  Target
0      0       1
1      2       0
2      1       1
3      0       1
4      1       1
5      0       0
6      0       1

In [8]:
#------one hot encoding
df_ohe=pd.get_dummies(df['Color'],prefix='Color')
df_combined=pd.concat([df,df_ohe],axis=1)
df_combined

   Color  Target  Color_0  Color_1  Color_2
0      0       1     True    False    False
1      2       0    False    False     True
2      1       1    False     True    False
3      0       1     True    False    False
4      1       1    False     True    False
5      0       0     True    False    False
6      0       1     True    False    False

In [10]:
#------one hot encoding
df_ohe=pd.get_dummies(df['Color'],)
df_combined=pd.concat([df,df_ohe],axis=1)
df_combined

   Color  Target   Blue  Green    Red
0   Blue       1   True  False  False
1    Red       0  False  False   True
2  Green       1  False   True  False
3   Blue       1   True  False  False
4  Green       1  False   True  False
5   Blue       0   True  False  False
6   Blue       1   True  False  False

In [11]:
df_ohe=pd.get_dummies(df['Color'],prefix='Color',dtype=int)
df_combined=pd.concat([df,df_ohe],axis=1)
df_combined

   Color  Target  Color_Blue  Color_Green  Color_Red
0   Blue       1           1            0          0
1    Red       0           0            0          1
2  Green       1           0            1          0
3   Blue       1           1            0          0
4  Green       1           0            1          0
5   Blue       0           1            0          0
6   Blue       1           1            0          0

In [12]:
# target encoding
mean_target=df.groupby('Color')['Target'].mean()
df['Encode_Target']=df['Color'].map(mean_target)
df

   Color  Target  Encode_Target
0   Blue       1           0.75
1    Red       0           0.00
2  Green       1           1.00
3   Blue       1           0.75
4  Green       1           1.00
5   Blue       0           0.75
6   Blue       1           0.75